apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "${REV}"
  labels:
    app: smart-home-api-server
  name: smart-home-api-server
  namespace: iot
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: smart-home-api-server
  template:
    metadata:
      labels:
        app: smart-home-api-server
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: smart-home-api-server
        image: loxtop/smart-home-api-server:${REV_TAG}
        imagePullPolicy: Always
        name: smart-home-api-server
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 700m  
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
