apiVersion: v1
kind: Service
metadata:
  labels:
    app: smart-home-websocket-server
  name: smart-home-websocket-server
  namespace: iot
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: smart-home-websocket-server
  sessionAffinity: None
  externalIPs:
  - 158.220.110.116
  type: LoadBalancer