# https://www.freecodecamp.org/news/how-to-enable-live-reload-on-docker-based-applications/
version: "3.8"
services:
    ws:
        container_name: ws_server
        restart: on-failure
        build:
            context: .
            dockerfile: server/Dockerfile
        volumes:
            - ./server:/app/server
        ports:
            - "8080:8080"
        command: >
            sh -c "node ."

    nextjs:
        container_name: nextjs
        restart: on-failure
        build: .
        volumes:
            - ./src:/app/src
        ports:
            - "3000:3000"
        command: >
            sh -c "npm start"
        depends_on:
            - ws

    # mssql:
    #     container_name: mssql
    #     hostname: mssql
    #     build: ./mssql
    #     ports:
    #         - 1433:1433
    #     environment:
    #         - ACCEPT_EULA=Y
    #         - SA_PASSWORD=asd.QWE.123
    #         - DATABASE_NAME=temp
    #         - MSSQL_PID=Express
    #     deploy:
    #         resources:
    #             limits:
    #                 memory: 1024M
